# Generated by Django 5.2.6 on 2025-10-01 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtomobil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Avtomobil nomi')),
                ('marka', models.CharField(max_length=100, verbose_name='Markasi')),
                ('yil', models.PositiveIntegerField(verbose_name='Ishlab chiqarilgan yil')),
                ('rang', models.CharField(max_length=50, verbose_name='Rangi')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('dvigatel', models.CharField(max_length=50, verbose_name='Dvigatel turi')),
                ('yurgan_km', models.PositiveIntegerField(verbose_name='Yurgan masofasi (km)')),
            ],
            options={
                'verbose_name': 'Avtomobil',
                'verbose_name_plural': 'Avtomobillar',
            },
        ),
        migrations.CreateModel(
            name='Egasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100, verbose_name='Egasi ismi')),
                ('familiya', models.CharField(max_length=100, verbose_name='Egasi familiyasi')),
                ('yosh', models.PositiveIntegerField(verbose_name='Yoshi')),
                ('telefon', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('manzil', models.CharField(max_length=200, verbose_name='Manzili')),
                ('avtomobil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egalar', to='app.avtomobil')),
            ],
            options={
                'verbose_name': 'Avtomobil egasi',
                'verbose_name_plural': 'Avtomobil egalari',
            },
        ),
    ]
